version: "3.9"

services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/web
    env_file:
      - .env
    depends_on:
      - db
      - broker

  db:
    image: postgres:14.6-alpine3.16
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  broker:
    build:
      context: ./broker
      args:
      - BROKER_PASS=${BROKER_PASS}
    restart: always
    volumes:
      - redis-data:/data
    hostname: ${BROKER_HOST}

volumes:
  postgres-data:
  static-data:
  redis-data: