# Generated by Django 4.1.2 on 2022-10-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bot_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
