# Generated by Django 4.1.2 on 2022-10-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_inspector_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notifier_option',
            field=models.CharField(choices=[('DOLLAR', 'Dollar'), ('PERCENT', 'Percent')], default='DOLLAR', max_length=255),
        ),
    ]
