# Generated by Django 4.1.2 on 2022-10-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_notifier_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='precision',
            name='is_blacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
