# Generated by Django 4.1.2 on 2022-11-01 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_precision_is_blacklisted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='is_notifier',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notifier_queue',
        ),
    ]
